name: Build Test CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  win_install:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm install

      # - name: Run preproduction script
      #   run: npm run preprod

      - name: Build for Windows
        run: npm run dist-windows
      - name: check for built dist files
        run: dir ./dist

  mac_install:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm install

      # - name: Run preproduction script
      #   run: npm run preprod

      - name: Build for Mac
        run: npm run dist-mac
      - name: check for built dist files
        run: ls ./dist

  linux_install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm install

      # - name: Run preproduction script
      #   run: npm run preprod

      - name: Build for Linux
        run: npm run dist-linux
      - name: check for built dist files
        run: ls ./dist
